app_kasir/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Change Password Routes...
Route::get('change-password', 'Auth\ChangePasswordController@getChangePassword')->name('change-password');
Route::post('change-password', 'Auth\ChangePasswordController@postChangePassword')->name('change-password');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'CartController@index')->name('home');
    Route::get('drafts', 'CartController@index')->name('cart.index');
    Route::get('drafts/{draftKey}', 'CartController@show')->name('cart.show');
    Route::post('drafts/{draftKey}', 'CartController@store')->name('cart.store');
    Route::post('cart/add-draft', 'CartController@add')->name('cart.add');
    Route::post('cart/add-draft-item/{draftKey}/{product}', 'CartController@addDraftItem')->name('cart.add-draft-item');
    Route::patch('cart/update-draft-item/{draftKey}', 'CartController@updateDraftItem')->name('cart.update-draft-item');
    Route::patch('cart/{draftKey}/proccess', 'CartController@proccess')->name('cart.draft-proccess');
    Route::delete('cart/remove-draft-item/{draftKey}', 'CartController@removeDraftItem')->name('cart.remove-draft-item');
    Route::delete('cart/empty/{draftKey}', 'CartController@empty')->name('cart.empty');
    Route::delete('cart/remove', 'CartController@remove')->name('cart.remove');
    Route::delete('cart/destroy', 'CartController@destroy')->name('cart.destroy');
    Route::get('products/price-list', ['as' => 'products.price-list', 'uses' => 'ProductsController@priceList']);
    Route::resource('products', 'ProductsController', ['except' => ['create', 'show', 'edit']]);
    Route::resource('units', 'UnitsController', ['except' => ['create', 'show', 'edit']]);
    Route::resource('users', 'UsersController', ['except' => ['create', 'show', 'edit']]);
    Route::get('transactions', ['as' => 'transactions.index', 'uses' => 'TransactionsController@index']);
    Route::get('transactions/{transaction}', ['as' => 'transactions.show', 'uses' => 'TransactionsController@show']);
    Route::get('transactions/{transaction}/pdf', ['as' => 'transactions.pdf', 'uses' => 'TransactionsController@pdf']);
    Route::get('transactions/{transaction}/receipt', ['as' => 'transactions.receipt', 'uses' => 'TransactionsController@receipt']);
    Route::group(['prefix' => 'reports'], function () {
        Route::get('sales', ['as' => 'reports.sales.index', 'uses' => 'Reports\SalesController@monthly']);
        Route::get('sales/daily', ['as' => 'reports.sales.daily', 'uses' => 'Reports\SalesController@daily']);
        Route::get('sales/monthly', ['as' => 'reports.sales.monthly', 'uses' => 'Reports\SalesController@monthly']);
        Route::get('sales/yearly', ['as' => 'reports.sales.yearly', 'uses' => 'Reports\SalesController@yearly']);
    });
    Route::post('backups/upload', ['as' => 'backups.upload', 'uses' => 'BackupsController@upload']);
    Route::post('backups/{fileName}/restore', ['as' => 'backups.restore', 'uses' => 'BackupsController@restore']);
    Route::get('backups/{fileName}/dl', ['as' => 'backups.download', 'uses' => 'BackupsController@download']);
    Route::resource('backups', 'BackupsController', ['except' => ['create', 'show', 'edit']]);

    Route::get('log-files', ['as' => 'log-files.index', 'uses' => 'LogFilesController@index']);
    Route::get('log-files/{filename}', ['as' => 'log-files.show', 'uses' => 'LogFilesController@show']);
    Route::get('log-files/{filename}/download', ['as' => 'log-files.download', 'uses' => 'LogFilesController@download']);
});

app_kasir/app/Transaction.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Transaction extends Model
{
    protected $casts = [
        'items'    => 'array',
        'customer' => 'array',
    ];

    public function getRouteKeyName()
    {
        return 'invoice_no';
    }

    public function getItemsCountAttribute($value)
    {
        $pcsCount = 0;
        foreach ($this->items as $item) {
            $pcsCount += $item['qty'];
        }

        return count($this->items).' Item, '.$pcsCount.' Pcs';
    }

    public function getExchange()
    {
        return $this->payment - $this->total;
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app_kasir/app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Cart\CartCollection;
use App\Cart\CashDraft;
use App\Cart\CreditDraft;
use App\Cart\Item;
use App\Product;
use Illuminate\Http\Request;

class CartController extends Controller
{
    private $cart;

    public function __construct()
    {
        $this->cart = new CartCollection();
    }

    public function index(Request $request)
    {
        $queriedProducts = [];
        $draft = $this->cart->content()->first();

        return view('cart.index', compact('draft', 'queriedProducts'));
    }

    public function show(Request $request, $draftKey)
    {
        $draft = $this->cart->get($draftKey);
        if (is_null($draft)) {
            flash(trans('transaction.draft_not_found'), 'danger');

            return redirect()->route('cart.index');
        }

        $query = $request->get('query');
        $queriedProducts = [];
        if ($query) {
            $queriedProducts = Product::where(function ($q) use ($query) {
                $q->where('name', 'like', '%'.$query.'%');
            })->with('unit')->get();
        }

        return view('cart.index', compact('draft', 'queriedProducts'));
    }

    public function add(Request $request)
    {
        if ($request->has('create-cash-draft')) {
            $this->cart->add(new CashDraft());
        } else {
            $this->cart->add(new CreditDraft());
        }

        return redirect()->route('cart.show', $this->cart->content()->last()->draftKey);
    }

    public function addDraftItem(Request $request, $draftKey, Product $product)
    {
        $item = new Item($product, $request->qty);
        $this->cart->addItemToDraft($draftKey, $item);

        flash(trans('cart.item_added', [
            'product_name' => $product->name.' ('.$product->unit->name.')',
            'qty'          => $request->qty,
        ]));

        if ($request->has('query')) {
            return redirect()->route('cart.show', [$draftKey, 'query' => $request->get('query')]);
        }

        return back();
    }

    public function updateDraftItem(Request $request, $draftKey)
    {
        $this->cart->updateDraftItem($draftKey, $request->item_key, $request->only('qty', 'item_discount'));

        return back();
    }

    public function removeDraftItem(Request $request, $draftKey)
    {
        $this->cart->removeItemFromDraft($draftKey, $request->item_index);

        return back();
    }

    public function empty($draftKey)
    {
        $this->cart->emptyDraft($draftKey);

        return redirect()->route('cart.index', $draftKey);
    }

    public function remove(Request $request)
    {
        $this->cart->removeDraft($request->draft_key);

        if ($this->cart->isEmpty()) {
            return redirect()->route('cart.index');
        }

        $lastDraft = $this->cart->content()->last();

        return redirect()->route('cart.show', $lastDraft->draftKey);
    }

    public function destroy()
    {
        $this->cart->destroy();
        flash(trans('transaction.draft_destroyed'), 'warning');

        return redirect()->route('cart.index');
    }

    public function proccess(Request $request, $draftKey)
    {
        $this->validate($request, [
            'customer.name'  => 'required|string|max:30',
            'customer.phone' => 'nullable|string|max:20',
            'total'          => 'required|numeric',
            'payment'        => 'required|numeric|min:'.$request->get('total').'|max:'.($request->get('total') + 100000),
            'notes'          => 'nullable|string|max:100',
        ], [
            'payment.min' => 'Pembayaran minimal '.format_rp($request->get('total')).'.',
            'payment.max' => 'Pembayaran terlalu besar '.format_rp($request->get('payment')).'.',
        ]);
        $draft = $this->cart->updateDraftAttributes($draftKey, $request->only('customer', 'notes', 'payment'));

        if ($draft->getItemsCount() == 0) {
            flash(trans('transaction.item_list_empty'), 'warning')->important();

            return redirect()->route('cart.show', [$draftKey]);
        }

        flash(trans('transaction.confirm_instruction', ['back_link' => link_to_route('cart.show', trans('app.back'), $draftKey)]), 'warning')->important();

        return redirect()->route('cart.show', [$draftKey, 'action' => 'confirm']);
    }

    public function store(Request $request, $draftKey)
    {
        $draft = $this->cart->get($draftKey);
        if (is_null($draft)) {
            return redirect()->route('cart.index');
        }

        $transaction = $draft->store();
        $draft->destroy();
        flash(trans('transaction.created', ['invoice_no' => $transaction->invoice_no]), 'success')->important();

        return redirect()->route('transactions.show', $transaction->invoice_no);
    }
}

app_kasir/resources/views/cart/partials/draft-confirm.blade.php
<div class="row">
    <div class="col-md-8">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">{{ trans('transaction.confirm') }}</h3></div>
            <div class="panel-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nama Item</th>
                            <th class="text-right">Harga Satuan</th>
                            <th class="text-right">Diskon per Item</th>
                            <th class="text-center">Qty</th>
                            <th class="text-right">Subtotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($draft->items() as $key => $item)
                        <tr>
                            <td>{{ $key + 1 }}</td>
                            <td>{{ $item->name }}</td>
                            <td class="text-right">{{ format_rp($item->price) }}</td>
                            <td class="text-right">{{ format_rp($item->item_discount) }}</td>
                            <td class="text-center">{{ $item->qty }}</td>
                            <td class="text-right">{{ format_rp($item->subtotal) }}</td>
                        </tr>
                        @empty
                        @endforelse
                    </tbody>
                    <tfoot>
                        <tr>


                            <th colspan="5" class="text-right">{{ trans('transaction.subtotal') }} :</th>
                            <th class="text-right">{{ format_rp($draft->getSubtotal()) }}</th>
                        </tr>
                        <tr>
                            <th colspan="5" class="text-right">{{ trans('transaction.discount_total') }} :</th>
                            <th class="text-right">{{ format_rp($draft->getDiscountTotal()) }}</th>
                        </tr>
                        <tr>
                            <th colspan="5" class="text-right">{{ trans('transaction.total') }} :</th>
                            <th class="text-right">{{ format_rp($draft->getTotal()) }}</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">{{ trans('transaction.detail') }}</h3></div>
            <div class="panel-body">
                <table class="table table-condensed">
                    <tbody>
                        <tr><td>{{ trans('transaction.customer_name') }}</td><td>{{ $draft->customer['name'] }}</td></tr>
                        <tr><td>{{ trans('transaction.customer_phone') }}</td><td>{{ $draft->customer['phone'] }}</td></tr>
                        <tr><td>{{ trans('transaction.payment') }}</td><th class="text-right">{{ format_rp($draft->payment) }}</th></tr>
                        <tr><td>{{ trans('transaction.total') }}</td><th class="text-right">{{ format_rp($draft->getTotal()) }}</th></tr>
                        <tr><td>{{ trans('transaction.exchange') }}</td><th class="text-right">{{ format_rp($draft->getExchange()) }}</th></tr>
                        <tr><td>{{ trans('transaction.notes') }}</td><td>{{ $draft->notes }}</td></tr>
                    </tbody>
                </table>
            </div>
            <div class="panel-footer">
                {{ Form::open(['route' => ['cart.store', $draft->draftKey]]) }}
                {{ Form::submit(trans('transaction.save'), ['id' => 'save-transaction-draft', 'class' => 'btn btn-success']) }}
                {{ link_to_route('cart.show', trans('app.back'), $draft->draftKey, ['class' => 'btn btn-default']) }}
                {{ Form::close() }}
            </div>
        </div>
    </div>
</div>

app_kasir/resources/views/cart/partials/draft-item-list.blade.php
<legend>
    {{ trans('transaction.items') }}
    <small class="text-muted">
        ({{ $draft->getItemsCount() }} Item, {{ $draft->getTotalQty() }} Pcs)
    </small>
</legend>
<div class="panel panel-default">
    <div class="panel-body table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nama Item</th>
                    <th>Harga Satuan</th>
                    <th class="text-right">Diskon per Item</th>
                    <th class="text-center">Qty</th>
                    <th class="text-right">Subtotal</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
            <?php $no = 1 ?>
            @forelse($draft->items() as $key => $item)
                <tr>
                    <td>{{ $no }} <?php $no++ ?></td>
                    <td>
                        {{ $item->name }} <br>
                        <small class="text-primary">({{ $item->unit }})</small>
                    </td>
                    <td>{{ format_rp($item->price) }}</td>
                        {{ Form::open(['route' => ['cart.update-draft-item', $draft->draftKey], 'method' => 'patch']) }}
                        {{ Form::hidden('item_key', $key) }}
                    <td class="text-right">
                        {{ Form::text('item_discount', $item->item_discount, [
                            'id' => 'item_discount-' . $key,
                            'style' => 'width:80px;text-align:right']
                        ) }}
                    </td>
                    <td class="text-center">
                        {{ Form::number('qty', $item->qty, [
                            'id' => 'qty-' . $key,
                            'style' => 'width:50px;text-align:center',
                            'min' => 1
                        ]) }}
                    </td>
                    <td class="text-right">{{ format_rp($item->subtotal) }}</td>
                        {{ Form::submit('update-item-' . $key, ['style'=>'display:none']) }}
                        {{ Form::close() }}
                    <td class="text-center show-on-hover-parent">
                        {!! FormField::delete([
                            'route' => ['cart.remove-draft-item', $draft->draftKey],
                            'onsubmit' => 'Yakin ingin menghapus Item ini?',
                            'class' => '',
                        ], 'x', ['id' => 'remove-item-' . $key, 'class' => 'btn btn-danger btn-xs show-on-hover','title' => 'Hapus item ini'], ['item_index' => $key]) !!}
                    </td>
                </tr>
            @empty
            @endforelse
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="5" class="text-right">{{ trans('transaction.subtotal') }} :</th>
                    <th class="text-right">{{ format_rp($draft->getSubtotal()) }}</th>
                    <th></th>
                </tr>
                <tr>
                    <th colspan="5" class="text-right">{{ trans('transaction.discount_total') }} :</th>
                    <th class="text-right">{{ format_rp($draft->getDiscountTotal()) }}</th>
                    <th></th>
                </tr>
                <tr>
                    <th colspan="5" class="text-right">{{ trans('transaction.total') }} :</th>
                    <th class="text-right">{{ format_rp($draft->getTotal()) }}</th>
                    <th></th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

app_kasir/resources/views/cart/partials/form-draft-detail.blade.php
<legend>{{ trans('transaction.detail') }}</legend>
{{ Form::open(['route' => ['cart.draft-proccess', $draft->draftKey], 'method' => 'patch']) }}
{!! FormField::text('customer[name]', ['label' => trans('transaction.customer_name'), 'value' => $draft->customer['name'], 'required' => true]) !!}
<div class="row">
    <div class="col-md-6">{!! FormField::text('customer[phone]', ['label' => trans('transaction.customer_phone'), 'value' => $draft->customer['phone']]) !!}</div>
    <div class="col-md-6">{!! FormField::price('payment', ['label' => trans('transaction.payment'), 'value' => $draft->payment, 'required' => true]) !!}</div>
</div>
{{ Form::hidden('total', $draft->getTotal()) }}
{!! FormField::textarea('notes', ['label' => trans('transaction.notes'), 'value' => $draft->notes]) !!}
{{ Form::submit(trans('transaction.proccess'), ['class' => 'btn btn-info']) }}
{{ Form::close() }}

app_kasir/resources/views/cart/partials/product-search-box.blade.php
<div class="panel panel-default" style="border-radius:0px">
    <div class="panel-heading">
        <form method="get" action="{{ route('cart.show', $draft->draftKey) }}">
            <label for="query">{{ trans('cart.product_search') }}</label>
            <input type="text" id="query" name="query" value="{{ request('query') }}" placeholder="{{ trans('cart.min_search_query') }}">
            <input type="submit" value="{{ trans('cart.product_search') }}" class="btn btn-sm">
            @if ($queriedProducts)
            {{ link_to_route('cart.show', trans('cart.search_box_cleanup'), [$draft->draftKey], ['class' => 'btn btn-sm']) }}
            @endif
        </form>
    </div>
    <div id="product-search-result-box">
    @includeWhen ($queriedProducts, 'cart.partials.product-search-result-box', [
        'draftType' => $draft->type,
        'draftKey' => $draft->draftKey
    ])
    </div>
</div>

app_kasir/resources/views/cart/partials/product-search-result-box.blade.php
<div class="panel-body table-responsive">
    <table class="table table-condensed">
        <thead>
            <tr>
                <th>{{ trans('product.name') }}</th>
                <th>{{ trans('product.unit') }}</th>
                <th>{{ trans('product.price') }} ({{ $draftType }})</th>
                <th>{{ trans('app.action') }}</th>
            </tr>
        </thead>
        <tbody>
            @forelse($queriedProducts as $product)
            <tr>
                <td>{{ $product->name }}</td>
                <td>{{ $product->unit->name }}</td>
                <td>{{ format_rp($product->getPrice($draftType)) }}</td>
                <td>
                    <form action="{{ route('cart.add-draft-item', [$draftKey, $product->id]) }}" method="post" style="display:inline">
                        <input type="hidden" name="query" value="{{ isset($query) ? $query : request('query') }}">
                        <input type="hidden" name="_token" value="{{ isset($formToken) ? $formToken : csrf_token() }}">
                        <input type="number" id="qty-{{ $product->id }}" style="width:50px" name="qty" value="1" min="1">
                        <input type="submit" id="add-product-{{ $product->id }}" value="Tambah">
                    </form>
                    @if ($loop->last)
                    {{ link_to_route('cart.show', trans('cart.search_box_cleanup'), [$draftKey], [
                        'class' => 'btn btn-sm btn-default pull-right'
                    ]) }}
                    @endif
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="3">
                    Produk tidak ditemukan dengan keyword : <strong><em>{{ request('query') }}</em></strong>
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>
</div>

app_kasir/resources/views/cart/partials/transaction-draft-tabs.blade.php
<?php use Facades\App\Cart\CartCollection; ?>
<ul class="nav nav-tabs transaction-draft-tabs">
    @foreach(CartCollection::content() as $key => $content)
        <?php $active = ($draft->draftKey == $key) ? 'class=active' : '' ?>
        <li {{ $active }} role="presentation">
            <a href="{{ route('cart.show', $key) }}">
                {{ trans('transaction.' . $content->type) }} - {{ $key }}
                <form action="{{ route('cart.remove') }}" method="post" style="display:inline" onsubmit="return confirm('Yakin ingin menghapus Draft Transaksi ini?')">
                    {{ csrf_field() }}
                    {{ method_field('delete') }}
                    <input type="hidden" name="draft_key" value="{{ $key }}">
                    <input type="submit" value="x" style="margin: -2px -7px 0px 0px" class="btn-link btn-xs pull-right">
                </form>
            </a>
        </li>
    @endforeach
</ul><!-- Tab panes -->